CREATE DATABASE IF NOT EXISTS uas_webdin;
USE uas_webdin;

CREATE TABLE IF NOT EXISTS kategori_barang (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_kategori VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS barang (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kode_barang VARCHAR(50) NOT NULL UNIQUE,
    nama_barang VARCHAR(255) NOT NULL,
    kategori_id INT NOT NULL,
    kondisi ENUM('Baik', 'Rusak Ringan', 'Rusak Berat') NOT NULL,
    lokasi VARCHAR(255) NOT NULL,
    jumlah INT NOT NULL DEFAULT 0,
    foto VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (kategori_id) REFERENCES kategori_barang(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'operator', 'viewer') NOT NULL DEFAULT 'viewer',
    reset_token VARCHAR(255),
    reset_token_expired_at DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insert Kategori Sample Data
INSERT INTO kategori_barang (nama_kategori) VALUES 
('Pendingin Ruangan'), 
('Komputer'), 
('Proyektor');

-- Insert Barang Sample Data
INSERT INTO barang (kode_barang, nama_barang, kategori_id, kondisi, lokasi, jumlah) VALUES 
('001-2026', 'AC Daikin 2 PK', 1, 'Baik', 'Lab 1', 2),
('002-2026', 'Komputer Desktop PC', 2, 'Baik', 'Lab 2', 20),
('003-2026', 'Proyektor Epson', 3, 'Baik', 'Ruang Kelas', 3);

-- Insert Users Sample Data
INSERT INTO users (nama, email, password, role) VALUES 
('Admin', 'admin@gmail.com', '$2b$10$q11IuIjkmnJlqE9HHG3h7e2hOlJn2YRecMaFpJMS8vrSRJ.uHxRx6', 'admin'),
('Operator', 'operator@gmail.com', '$2b$10$wUt/q6gTWZSMM5.ipCpaiedhkDn8FYMBFAQzjZhXnA.2Ue3/NWgdi', 'operator'),
('Viewer', 'viewer@gmail.com', '$2b$10$EOifs.wNWvnZTjPc6iMEdeSy4sNyX/ZEYCuv9biuUEvu7AuHmNcH2', 'viewer');

-- Note: In application, hash is properly generated by bcrypt.
